export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST'
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS'
export const LESSON_LIST_FAIL = 'LESSON_LIST_FAIL'


export const LESSON_DETAILS_LIST_REQUEST = 'LESSON_DETAILS_LIST_REQUEST'
export const LESSON_DETAILS_LIST_SUCCESS = 'LESSON_DETAILS_LIST_SUCCESS'
export const LESSON_DETAILS_LIST_FAIL = 'LESSON_DETAILS_LIST_FAIL'
