# Generated by Django 4.2.2 on 2023-09-18 19:22

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('decsription', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post-images/')),
                ('is_featured', models.BooleanField(blank=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('category_name', models.ForeignKey(blank=True, default='general', null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.category')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
