# Generated by Django 4.2.5 on 2023-09-24 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_content_lesson_subject_remove_post_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.ForeignKey(blank=True, default='general', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='base.content'),
        ),
    ]
