# Generated by Django 4.2.5 on 2023-09-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subject_color_alter_lesson_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='color',
            new_name='color_code',
        ),
    ]
