# Generated by Django 4.2.5 on 2023-09-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_color_subject_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, default='general', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='base.subject'),
        ),
    ]
