# Generated by Django 4.2.5 on 2023-09-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
    ]
